.PHONY: all
ROOT_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

clang-r399163b/bin/clang:
	echo "Clang build stub"

clean:
	echo "Clang clean stub"

distclean: clean
	echo "Clang distclean stub"

all: clang-r399163b/bin/clang
