.PHONY: all
VERSION=30
ROOT_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

bin/gcc:
	echo "GCC-5.1.0 build stub"

clean:
	echo "GCC-5.1.0 clean stub"

distclean: clean
	rm -rf ../../../../wd/gcc-5.1.0

all: bin/gcc
